// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Abstract class representing an action a player can take 
 */
public abstract class Action {
	/** explains what the action is */
	protected String actionExplanation; 

	/**
	 * Returns a string explaining what the action is
	 * @return value of actionExplanation attribute
	 */
	public String getActionExplanation() {
		return actionExplanation;
	}

	/**
	 * Execute the action
	 * @param game Game instance 
	 * @param player Player which action is being performed by
	 */
	public abstract void execute(Game game, Player player);

	/**
	 * Undo the action
	 * @param game Current game instance 
	 * @param player Player which the action is being undone for 
	 */
	public abstract void undo(Game game, Player player);
}
