// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package CatanGame; 

import java.util.ArrayList;
import java.util.List;

/**
 * Agent that decides what actions a player should take
 */
public class Agent implements PlayerAgent {
	/** agent's identifier */
	private int id;
	/** player controlled by this agent */
	private Player controls; 
	/** strategy for selecting actions */
	private ActionSelectionStrat strategy;

	/**
	 * Default constructor with id -1
	 */
	public Agent() {
			this(-1);
	}

	/**
	 * Constructor but it has specified id and a default random strategy
	 * @param id to identify the agent
	 */
	public Agent(int id) {
			this.id=id;
			this.strategy = new RandomStratAction();
	}
	/**
	 * Constructor with but with id and strategy
	 * @param id to identify the agent
	 * @param strategy The selection strategy for actions that will be used
	 */
	public Agent(int id, ActionSelectionStrat strategy) {
			this.id =id;
			this.strategy =strategy;
	}



	/**
	 * Chooses an action for the player to take
	 * @param player player making the decision
	 * @param game current game state
	 * @return action to execute
	 */
	public Action chooseAction(Player player, Game game) {
			Board board=game.getBoard(); // gameboard
			ResourceHand hand=player.getResourceHand(); // players resources
			List<Action> buildActions=new ArrayList<>(); // possible build actions
			if (hand.canAfford(BuildCosts.ROAD)) {
					buildActions.addAll(getLegalRoadActions(player,board));
			}
			if (hand.canAfford(BuildCosts.SETTLEMENT)) {
					buildActions.addAll(getLegalSettlementActions(player,board));
			}
			if (hand.canAfford(BuildCosts.CITY)) {
					buildActions.addAll(getLegalCityActions(player));
			}
			List<Action> allActions = new ArrayList<>(buildActions); // all actions allowed and available
			allActions.add(new Pass());
			return strategy.selectAction(allActions,player,game);
	}

	/**
	 * @return agent's id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @return player controlled by agent
	 */
	public Player getControlledPlayer() {
		return controls;
	}

	/**
	 * Sets the player controlled by this agent
	 * @param controls player to control
	 */
	public void setControlledPlayer(Player controls) {
		this.controls = controls;
	}

	private List<Action> getLegalRoadActions(Player player, Board board) {
		List<Action> actions = new ArrayList<>();
		for (Edge edge : board.getEdges()) {
			if (edge == null || edge.edgeOccupied()) {
				continue;
			}
			if (isRoadPlacementConnected(edge, player)) {
				actions.add(new BuildRoad(edge));
			}
		}
		return actions;
	}

	private List<Action> getLegalSettlementActions(Player player, Board board) {
		List<Action> actions = new ArrayList<>();
		for (Node node : board.getNodes()) {
			if (node == null || node.nodeOccupied()) {
				continue;
			}
			if (!satisfiesDistanceRule(node)) {
				continue;
			}
			if (isConnectedToPlayerRoad(node, player)) {
				actions.add(new BuildSettlement(node));
			}
		}
		return actions;
	}

	private List<Action> getLegalCityActions(Player player) {
		List<Action> actions = new ArrayList<>();
		for (Building building : player.getBuildings()) {
			if (building instanceof Settlement) {
				actions.add(new BuildCity(building.getLocation()));
			}
		}
		return actions;
	}

	private boolean isRoadPlacementConnected(Edge edge, Player player) {
		Node first = edge.getFirst();
		Node second = edge.getSecond();

		if (isNodeOwnedByPlayer(first, player) || isNodeOwnedByPlayer(second, player)) {
			return true;
		}

		for (Road road : player.getRoads()) {
			Edge ownedEdge = road.getRoadLocation();
			if (ownedEdge == null) {
				continue;
			}
			if (sharesEndpoint(edge, ownedEdge)) {
				return true;
			}
		}
		return false;
	}

	private boolean isConnectedToPlayerRoad(Node node, Player player) {
		for (Road road : player.getRoads()) {
			Edge edge = road.getRoadLocation();
			if (edge == null) {
				continue;
			}
			if (edge.getFirst() == node || edge.getSecond() == node) {
				return true;
			}
		}
		return false;
	}

	private boolean satisfiesDistanceRule(Node node) {
		for (Node adjacentNode : node.getAdjacentNodes()) {
			if (adjacentNode == null) {
				continue;
			}
			if (adjacentNode.getBuilding() != null) {
				return false;
			}
		}
		return true;
	}

	private boolean isNodeOwnedByPlayer(Node node, Player player) {
		Building building = node.getBuilding();
		return building != null && building.getOwner() == player;
	}

	private boolean sharesEndpoint(Edge first, Edge second) {
		return first.getFirst() == second.getFirst()
			|| first.getFirst() == second.getSecond()
			|| first.getSecond() == second.getFirst()
			|| first.getSecond() == second.getSecond();
	}
}