// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package CatanGame; 

public class Agent {
	private int id;
	private Player controls; 

	/**
	 * 
	 * @param player 
	 * @param game 
	 * @return 
	 */
	public Action chooseAction(Player player, Game game) {
	}
}