// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Edge[] edges;

	/**
	 * 
	 */
	public void initializeMap() {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Tile getTileById(Integer id) {
	}

	public List<Tile> getTilesByToken(int token) {
		List<Tile> sameTokenNumberTiles = new ArrayList<>();
		for (Tile tile: tiles) {
			if (token==tile.getNumberToken()) {
				sameTokenNumberTiles.add(tile);
			}
		}
		
		return sameTokenNumberTiles;
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Node getNodeById(Integer id) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Edge getEdgeById(Integer id) {
	}
}
