// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Class to build a road at an edge for a player 
 */
public class BuildRoad extends Action {
	private Edge edge; // Edge where road will be built 

	/**
	 * Constructor to initialize the edge where the road will be built and set the action explanation
	 * @param edge Edge where road will be built
	 */
	public BuildRoad(Edge edge) {

		// Verify building location is not already occupie d
		if(edge.edgeOccupied()) {
			throw new IllegalArgumentException("There is already a road on the edge"); 
		}
		this.edge = edge;
		this.actionExplanation = "Built a road at an edge"; 
	}

	/**
	 * Executes the action of building a road 
	 * @param game Game instance 
	 * @param player player which action is being performed by
	 */
	@Override
	public void execute(Game game, Player player) {
		Road road = new Road(player, edge);
		game.addRoad(road);
		player.addRoad(road);
	}
}
