// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Class that builds a city at a node for a player
 */
public class BuildCity extends Action {
	/** location where city will be built */
	private Node node; 

	/**
	 * Constructor to create the city 
	 * @param node Node where city will be built
	 */
	public BuildCity(Node node) {
		this.node = node;
		if (node == null) {
			this.actionExplanation = "skip invalid city upgrade";
			return;
		}
		this.actionExplanation = "upgrade settlement to city at node " + node.getId();
	}
	/**
	 * Executes the action of building a city 
	 * @param game Game instance
	 * @param player Player which action is being performed by
	 */
	@Override 
	public void execute(Game game, Player player) {
		if (node == null) {
			return;
		}
		Building currentBuilding = node.getBuilding(); // existing building at node
		if (!(currentBuilding instanceof Settlement) || currentBuilding.getOwner() != player) {
			return;
		}

		ResourceHand hand = player.getResourceHand(); // player's resources
		if (!hand.canAfford(BuildCosts.CITY)) {
			return;
		}
		hand.spend(BuildCosts.CITY);

		player.deleteBuilding(currentBuilding);
		game.removeBuilding(currentBuilding);

		City city = new City(player, node); // new city to build
		game.addBuilding(city); 
		player.addBuilding(city);
		player.collectPoints(city.getVictoryPoints() - currentBuilding.getVictoryPoints());
	}
}
