// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Class that builds a settlement at a node for a player
 */
public class BuildSettlement extends Action {
	private Node node; // Location where settlement will be built
	
	/**
	 * Constructor to initialize the node where the settlement will be built and set the action explanation
	 * @param node Node where settlement will be built
	 */
	public BuildSettlement(Node node) {

		// Verify building location is not already occupied 
		if(node.nodeOccupied()) {
			throw new IllegalArgumentException("There is already a building on the node");
		}
		this.node = node; 
		this.actionExplanation = "Build a settlement at node " + node.getId(); 
	}

	/**
	 * Executes the action of building a settlement 
	 * @param game Game instance
	 * @param player Player which action is being performed by 
	 */
	@Override
	public void execute(Game game, Player player) {
		Settlement settlement = new Settlement(player, node); 
		game.addBuilding(settlement);
		player.addBuilding(settlement);
		player.collectPoints(settlement.getVictoryPoints());
	}
}
