// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Abstract class representing a building
 */
public abstract class Building {
	/** player who owns the building */
	private Player owner; 
	/** node where building is placed */
	private Node location;

	/**
	 * Constructor for building
	 * @param owner player who owns it
	 * @param location where it's built
	 */
	public Building(Player owner, Node location) {
		this.owner = owner;
		this.location = location;
		location.addBuilding(this);
	}

	/**
	 * @return victory points for this building
	 */
	public abstract int getVictoryPoints();

	/**
	 * @return location of building
	 */
	public Node getLocation() {
		return location;
	}

	/**
	 * @return owner of building
	 */
	public Player getOwner() {
		return owner;
	}
}
