// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Class that builds a city at a node for a player
 */
public class BuildCity extends Action {
	private Node node; // Location where city will be built 

	/**
	 * Constructor to create the city 
	 * @param node Node where city will be built
	 */
	public BuildCity(Node node) {
		
		// Verify building location is not already occupied 
		if(node.nodeOccupied()) {
			throw new IllegalArgumentException("There is already a building on the node");
		}
		this.node = node;
		this.actionExplanation = "Build a city at node " + node.getId();
	}
	/**
	 * Executes the action of building a city 
	 * @param game Game instance
	 * @param player Player which action is being performed by
	 */
	@Override 
	public void execute(Game game, Player player) {
		City city = new City(player, node);
		game.addBuilding(city); 
		player.addBuilding(city);
		player.collectPoints(city.getVictoryPoints());
	}
}
