// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Class that builds a settlement at a node for a player
 */
public class BuildSettlement extends Action {
	/** location where settlement will be built */
	private Node node; 
	
	/**
	 * Constructor to initialize the node where the settlement will be built and set the action explanation
	 * @param node Node where settlement will be built
	 */
	public BuildSettlement(Node node) {
		this.node = node; 
		if (node == null) {
			this.actionExplanation = "skip invalid settlement placement";
			return;
		}
		this.actionExplanation = "build a settlement at node " + node.getId(); 
	}

	/**
	 * Executes the action of building a settlement 
	 * @param game Game instance
	 * @param player Player which action is being performed by 
	 */
	@Override
	public void execute(Game game, Player player) {
		if (node == null || node.nodeOccupied()) {
			return;
		}
		for (Node adjacentNode : node.getAdjacentNodes()) {
			if (adjacentNode != null && adjacentNode.getBuilding() != null) {
				return;
			}
		}
		ResourceHand hand = player.getResourceHand(); // player's resources
		if (!hand.canAfford(BuildCosts.SETTLEMENT)) {
			return;
		}
		hand.spend(BuildCosts.SETTLEMENT);
		Settlement settlement = new Settlement(player, node); // new settlement to build
		game.addBuilding(settlement);
		player.addBuilding(settlement);
		player.collectPoints(settlement.getVictoryPoints());
	}
}
