// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public abstract class Building {
	/**
	 * 
	 */
	protected Player owner;
	/**
	 * 
	 */
	private Node location;

	/**
	 * 
	 * @return 
	 */
	public Integer getVictoryPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getLocation() {
		return location;
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
		return owner;
	}
}
