// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Class to build a road at an edge for a player 
 */
public class BuildRoad extends Action {
	/** edge where road will be built */
	private Edge edge; 

	/**
	 * Constructor to initialize the edge where the road will be built and set the action explanation
	 * @param edge Edge where road will be built
	 */
	public BuildRoad(Edge edge) {
		this.edge = edge;
		if (edge == null) {
			this.actionExplanation = "skip invalid road placement";
			return;
		}
		this.actionExplanation = "build a road on edge (" + edge.getFirst().getId() + ", " + edge.getSecond().getId() + ")"; 
	}

	/**
	 * Executes the action of building a road 
	 * @param game Game instance 
	 * @param player player which action is being performed by
	 */
	@Override
	public void execute(Game game, Player player) {
		if (edge == null || edge.edgeOccupied()) {
			return;
		}
		ResourceHand hand = player.getResourceHand(); // player's resources
		if (!hand.canAfford(BuildCosts.ROAD)) {
			return;
		}
		hand.spend(BuildCosts.ROAD);
		Road road = new Road(player, edge); // new road to build
		game.addRoad(road);
		player.addRoad(road);
	}
}
