// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/**
 * Interface for dice rolling
 */
public interface Dice {
	/**
	 * Rolls the dice
	 * @return result of the roll
	 */
	public int roll();
}
