// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

import java.util.Map;
import java.util.HashMap;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private Integer currentRound;
	/**
	 * 
	 */
	private Integer maxRounds;
	/**
	 * 
	 */
	private Boolean gameFinished;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private Dice dice;

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void playRound() {
	}

	public void resourceDistributor(int rollResult) {
		Map<Player, Integer> playersTouchingTile = getPlayersOnTile(rollResult);
		for (Map.Entry<Player, Integer> input: playersTouchingTile.entrySet()) {
			Player player = input.getKey();
			Integer cardsToGive = input.getValue();

			ResourceType resourceType = getTileResourceType(rollResult);
			ResourceHand resourceHand = player.getResourceHand();

			resourceHand.add(resourceType, cardsToGive);
		}
	}

	public Map<Player, Integer> getPlayersOnTile(int rollResult) {
		Map<Player, Integer> playersTouchingTile = new HashMap<>();
		int numberOfCardsToGive = 0;

		Tile tile = board.getTileById(rollResult);
		Node[] adjacentNodes = tile.getAdjacentNodes();
		for (Node node: adjacentNodes){
			Building building = node.getBuilding();
			if (building instanceof Settlement) {
				numberOfCardsToGive = 1;
			}
			else {
				numberOfCardsToGive = 2;
			}
			playersTouchingTile.put(building.getOwner(), numberOfCardsToGive);
		}
		
		return playersTouchingTile;
	}

	public ResourceType getTileResourceType(int rollResult) {
		Tile tile = board.getTileById(rollResult);
		ResourceType resourceType = tile.getResourceType();
		return resourceType;
	}

	/**
	 * 
	 * @return 
	 */
	public Boolean checkTerminationCondition() {
	}

	/**
	 * 
	 */
	public void printRoundSummary() {
	}

	/**
	 * 
	 * @param board 
	 * @param players 
	 * @param dice 
	 */
	public void Game(Board board, Player[] players, Dice dice) {
	}
}
