// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

/************************************************************/
/**
 *
 */
public class Game {
	/** The current round number */
	private int currentRound;
	/** maximum rounds before game ends */
	private int maxRounds;
	/** whether the game has ended */
	private boolean gameFinished;
	/** game board */
	private Board board;
	/** array of players in the game */
	private Player[] players;
	/** dice used for rolling */
	private Dice dice;
	/** list of all buildings in the game */
	private List<Building> buildings;
	/** list of all roads in the game */
	private List<Road> roads;
	/** random number generator for initial placements */
	private Random random;
	/** scanner for pausing between AI turns (keep forward) */
	private Scanner scanner;
	/** path for game state JSON export */
	private String gameStatePath;

	/**
	 * Constructor for the game
	 * @param board game board
	 * @param players array of players
	 * @param dice dice to use
	 * @param maxRounds max number of rounds
	 */
	public Game(Board board, Player[] players, Dice dice, int maxRounds) {
		this.board = (board == null) ? new Board() : board;
		this.players = sanitizePlayers(players);
		this.dice = (dice == null) ? new MultiDice() : dice;
		this.maxRounds = normalizeMaxRounds(maxRounds);
		this.currentRound = 0;
		this.gameFinished = false;
		this.buildings = new ArrayList<>();
		this.roads = new ArrayList<>();
		this.random = new Random();

		for (int i = 0; i < this.players.length; i++) {
			Player player = this.players[i]; // each player in array
			if (player != null && player.getId() <= 0) {
				player.setId(i + 1);
			}
		}
	}

	/**
	 * Sets the scanner used for keep-forward pausing
	 * @param scanner scanner for human input
	 */
	public void setScanner(Scanner scanner) {
		this.scanner = scanner;
	}

	/**
	 * Sets the file path for JSON game state export
	 * @param path file path for game state output
	 */
	public void setGameStatePath(String path) {
		this.gameStatePath = path;
	}

	/**
	 * Starts the game and runs until termination
	 */
	public void start() {
		if (board == null) {
			board = new Board();
		}
		if (board.getNodeById(0) == null || board.getTileById(0) == null) {
			board.initializeMap();
		}

		runInitialPlacement();
		exportGameState();

		while (!checkTerminationCondition()) {
			playRound();
		}

		printFinalResults();
		exportGameState();
	}

	/**
	 * Plays a single round where all players take turns
	 */
	public void playRound() {
		currentRound++;
		if (players == null) {
			return;
		}
		for (Player player : players) {
			if (player == null) {
				continue;
			}

			if (player.isInteractive()) {
				playHumanTurn(player);
			} else {
				playAiTurn(player);
			}

			exportGameState();

			if (checkTerminationCondition()) {
				break;
			}
		}
		printRoundSummary();
	}

	/**
	 * Handles an AI player's turn
	 */
	private void playAiTurn(Player player) {
		int rollResult = dice.roll(); // dice result for this turn

		if (rollResult == 7) {
			handleRobber(player);
		} else {
			resourceDistributor(rollResult);
		}

		Action action = player.takeTurn(this); // action chosen by player
		if (action == null) {
			action = new Pass();
		}
		System.out.println("[" + currentRound + "] / [" + player.getId() + "]: rolled " + rollResult + ", " + action.getActionExplanation());

		// Keep forward: pause for human to read AI actions
		if (hasHumanPlayer() && scanner != null) {
			System.out.println("Press Enter to continue...");
			if (scanner.hasNextLine()) {
				scanner.nextLine();
			}
		}
	}

	/**
	 * Handles a human player's turn
	 */
	private void playHumanTurn(Player player) {
		System.out.println("\n=== Your turn (Player " + player.getId() + ") ===");
		System.out.println("Type 'roll' to roll the dice.");

		int rollResult = dice.roll(); // dice result for this turn
		// The HumanAgent handles the roll command; we pre-roll and display the result
		// after the agent processes the "roll" command

		// Store the roll result so the agent can trigger it
		this.lastRollResult = rollResult;

		Action action = player.takeTurn(this); // HumanAgent manages the full turn
		if (action == null) {
			action = new Pass();
		}

		System.out.println("[" + currentRound + "] / [" + player.getId() + "]: " + action.getActionExplanation());
	}

	/** Stores last dice roll for human turn flow */
	private int lastRollResult;

	/**
	 * Called by HumanAgent after the human types "roll".
	 * Rolls dice, distributes resources, and returns the result.
	 * @return the dice roll result
	 */
	public int rollDiceForHuman() {
		int rollResult = lastRollResult;
		if (rollResult == 7) {
			handleRobber(null);
		} else {
			resourceDistributor(rollResult);
		}
		return rollResult;
	}

	/**
	 * Handles robber activation when a 7 is rolled.
	 * Moves robber to random non-desert tile and steals from a qualifying player.
	 */
	private void handleRobber(Player currentPlayer) {
		for (Player p: players) {
			if (p==null) {
				continue;
			}

			ResourceHand hand = p.getResourceHand();


			if (hand.totalCards()>7) {
				int toDiscard = hand.totalCards()/2;
				int discarded = 0;
				for (ResourceType type: ResourceType.values()) {
					if (discarded >= toDiscard) {
						break;
					}

					if (ResourceType.DESERT == type) {
						continue;
					}

					int count = hand.getCount(type);
					int remove = Math.min(count, toDiscard-discarded);
					if (remove> 0) {
						hand.remove(type, remove);
						discarded = discarded+ remove;
					}
				}

				System.out.println(currentRound+ " Player "+ p.getId()+ " discarded " +toDiscard+" cards (had more than 7)");
			}
		}

		Robber robber = board.getRobber();
		if (robber == null) {
			return;
		}

		// Find a random tile that is not desert and not already robbed
		List<Tile> candidates = new ArrayList<>();
		for (Tile tile : board.getTiles()) {
			if (tile == null) {
				continue;
			}
			if (tile.getResourceType() == ResourceType.DESERT) {
				continue;
			}
			if (tile == robber.getCurrentTile()) {
				continue;
			}
			candidates.add(tile);
		}

		if (candidates.isEmpty()) {
			return;
		}

		Tile targetTile = candidates.get(random.nextInt(candidates.size()));
		robber.moveRobber(targetTile);
		System.out.println("[" + currentRound + "] Robber moved to tile " + targetTile.getId() + " (" + targetTile.getResourceType() + ")");

		// Find qualifying players with buildings adjacent to robbed tile
		List<Player> qualifyingPlayers = new ArrayList<>();
		for (Node node : targetTile.getAdjacentNodes()) {
			if (node == null || node.getBuilding() == null) {
				continue;
			}
			Player owner = node.getBuilding().getOwner();
			if (owner != currentPlayer && !qualifyingPlayers.contains(owner)) {
				qualifyingPlayers.add(owner);
			}
		}

		if (qualifyingPlayers.isEmpty()) {
			return;
		}

		// Randomly select a player to steal from
		Player victim = qualifyingPlayers.get(random.nextInt(qualifyingPlayers.size()));
		ResourceHand victimHand = victim.getResourceHand();

		// Build list of stealable resource types
		List<ResourceType> stealable = new ArrayList<>();
		for (ResourceType type : ResourceType.values()) {
			if (type == ResourceType.DESERT) {
				continue;
			}
			if (victimHand.getCount(type) > 0) {
				stealable.add(type);
			}
		}

		if (stealable.isEmpty()) {
			return;
		}

		ResourceType stolenType = stealable.get(random.nextInt(stealable.size()));
		victimHand.remove(stolenType, 1);
		if (currentPlayer != null) {
			currentPlayer.getResourceHand().add(stolenType, 1);
		}
		System.out.println("[" + currentRound + "] Stole 1 " + stolenType + " from Player " + victim.getId());
	}

	/**
	 * Distributes resources to players based on dice roll
	 * @param rollResult the dice roll result
	 */
	public void resourceDistributor(int rollResult) {
		List<ResourceDistribution> distribution = getPlayersOnTile(rollResult); // list of distributions to give

		for (ResourceDistribution input: distribution) {
			Player player = input.getPlayer(); // player receiving resources
			ResourceHand resourceHand = player.getResourceHand(); // their current hand
			resourceHand.add(input.getResourceType(), input.getNumberOfCardsToGive());
		}
	}

	/**
	 * Gets list of resource distributions for players with buildings on rolled tile
	 * @param rollResult the dice roll
	 * @return list of resource distributions
	 */
	public List<ResourceDistribution> getPlayersOnTile(int rollResult) {
		List<ResourceDistribution> distribution = new ArrayList<>(); // distributions to give out
		List<Tile> sameTokenNumberTiles = new ArrayList<>(); // tiles with matching token

		if (board == null) {
			return distribution;
		}

		sameTokenNumberTiles = board.getTilesByToken(rollResult);

		for (Tile tile: sameTokenNumberTiles){
			if (tile == null) {
				continue;
			}
			Node[] adjacentNodes = tile.getAdjacentNodes(); // nodes around tile
			ResourceType resourceType = tile.getResourceType(); // resource this tile gives
			if (resourceType == null || resourceType == ResourceType.DESERT) {
				continue;
			}

			for (Node node: adjacentNodes){
				if (node == null) {
					continue;
				}
				Building building = node.getBuilding(); // building on this node
				if (building == null) {
					continue;
				}

				int numberOfCardsToGive; // amount based on building type
				if (building instanceof Settlement) {
					numberOfCardsToGive = 1;
				}
				else if (building instanceof City) {
					numberOfCardsToGive = 2;
				} else {
					continue;
				}

				Player owner = building.getOwner(); // player who owns the building
				distribution.add(new ResourceDistribution(owner, numberOfCardsToGive, resourceType));
			}
		}

		return distribution;
	}

	/**
	 * Checks if game should end
	 * @return true if game should terminate
	 */
	public boolean checkTerminationCondition() {
		if (gameFinished) {
			return true;
		}
		if (currentRound >= maxRounds) {
			gameFinished = true;
			return true;
		}
		for (Player player : players) {
			if (player == null) {
				continue;
			}
			if (player.getVictoryPoints() >= 10) {
				gameFinished = true;
				return true;
			}
		}
		return false;
	}

	/**
	 * Prints victory points for all players at end of round
	 */
	public void printRoundSummary() {
		for (Player player : players) {
			if (player == null) {
				continue;
			}
			System.out.println("[" + currentRound + "] / [" + player.getId() + "]: victory points = " + player.getVictoryPoints());
		}
	}

	/**
	 * Alternate constructor with default max rounds
	 * @param board game board
	 * @param players array of players
	 * @param dice dice to use
	 */
	public Game(Board board, Player[] players, Dice dice) {
		this(board, players, dice, 50);
	}

	/**
	 * Adds a building to the game
	 * @param building building to add
	 */
	public void addBuilding(Building building) {
		if (building == null) {
			return;
		}
		buildings.add(building);
	}

	/**
	 * Removes a building from the game
	 * @param building building to remove
	 */
	public void removeBuilding(Building building) {
		if (building == null) {
			return;
		}
		buildings.remove(building);
	}

	/**
	 * Adds a road to the game
	 * @param road road to add
	 */
	public void addRoad(Road road) {
		if (road == null || road.getRoadLocation() == null || road.getRoadLocation().getRoad() != road) {
			return;
		}
		roads.add(road);
	}

	/**
	 * Removes a road from the game.
	 * @param road road to remove
	 */
	public void removeRoad(Road road) {
		if (road == null) {
			return;
		}
		roads.remove(road);
	}

	/**
	 * @return game board
	 */
	public Board getBoard() {
		return board;
	}

	/**
	 * @return copy of players array
	 */
	public Player[] getPlayers() {
		return players == null ? new Player[0] : players.clone();
	}

	/**
	 * @return current round number
	 */
	public int getCurrentRound() {
		return currentRound;
	}

	/**
	 * @return list of all buildings
	 */
	public List<Building> getBuildings() {
		return new ArrayList<>(buildings);
	}

	/**
	 * @return list of all roads
	 */
	public List<Road> getRoads() {
		return new ArrayList<>(roads);
	}

	private boolean hasHumanPlayer() {
		for (Player player : players) {
			if (player != null && player.isInteractive()) {
				return true;
			}
		}
		return false;
	}

	private void exportGameState() {
		if (gameStatePath != null) {
			GameStateExporter.export(this, gameStatePath);
		}
	}

	private void runInitialPlacement() {
		int[] snakeOrder = new int[] {0, 1, 2, 3, 3, 2, 1, 0};
		int[] placementCount = new int[] {0, 0, 0, 0};

		for (int playerIndex : snakeOrder) {
			Player player = players[playerIndex];
			if (player == null) {
				continue;
			}
			Node settlementNode = chooseRandomInitialSettlementNode();
			if (settlementNode == null) {
				continue;
			}
			placeInitialSettlement(player, settlementNode);
			System.out.println("[0] / [" + player.getId() + "]: initial settlement at node " + settlementNode.getId());

			Edge roadEdge = chooseRandomInitialRoadEdge(settlementNode);
			if (roadEdge != null) {
				placeInitialRoad(player, roadEdge);
				System.out.println("[0] / [" + player.getId() + "]: initial road on edge (" + roadEdge.getFirst().getId() + ", " + roadEdge.getSecond().getId() + ")");
			}

			placementCount[playerIndex]++;
			if (placementCount[playerIndex] == 2) {
				grantInitialResources(player, settlementNode);
			}
		}
	}

	private Node chooseRandomInitialSettlementNode() {
		List<Node> candidateNodes = new ArrayList<>();
		for (Node node : board.getNodes()) {
			if (node == null) {
				continue;
			}
			if (!node.nodeOccupied() && satisfiesDistanceRule(node)) {
				candidateNodes.add(node);
			}
		}
		if (candidateNodes.isEmpty()) {
			return null;
		}
		return candidateNodes.get(random.nextInt(candidateNodes.size()));
	}

	private Edge chooseRandomInitialRoadEdge(Node anchorNode) {
		if (anchorNode == null) {
			return null;
		}
		List<Edge> candidateEdges = new ArrayList<>();
		for (Edge edge : board.getEdges()) {
			if (edge == null || edge.edgeOccupied()) {
				continue;
			}
			if (edge.getFirst() == anchorNode || edge.getSecond() == anchorNode) {
				candidateEdges.add(edge);
			}
		}
		if (candidateEdges.isEmpty()) {
			return null;
		}
		return candidateEdges.get(random.nextInt(candidateEdges.size()));
	}

	private boolean satisfiesDistanceRule(Node node) {
		for (Node adjacentNode : node.getAdjacentNodes()) {
			if (adjacentNode != null && adjacentNode.getBuilding() != null) {
				return false;
			}
		}
		return true;
	}

	private void placeInitialSettlement(Player player, Node node) {
		if (player == null || node == null || node.nodeOccupied()) {
			return;
		}
		Settlement settlement = new Settlement(player, node);
		addBuilding(settlement);
		player.addBuilding(settlement);
		player.collectPoints(settlement.getVictoryPoints());
	}

	private void placeInitialRoad(Player player, Edge edge) {
		if (player == null || edge == null || edge.edgeOccupied()) {
			return;
		}
		Road road = new Road(player, edge);
		addRoad(road);
		player.addRoad(road);
	}

	private void grantInitialResources(Player player, Node secondSettlementNode) {
		if (player == null || secondSettlementNode == null) {
			return;
		}
		for (Tile tile : board.getTiles()) {
			if (tile == null) {
				continue;
			}
			ResourceType type = tile.getResourceType();
			if (type == null || type == ResourceType.DESERT) {
				continue;
			}
			for (Node adjacentNode : tile.getAdjacentNodes()) {
				if (adjacentNode != null && adjacentNode == secondSettlementNode) {
					player.getResourceHand().add(type, 1);
					break;
				}
			}
		}
	}

	private void printFinalResults() {
		System.out.println("=== Game finished after " + currentRound + " rounds ===");
		int highestVp = Integer.MIN_VALUE;
		for (Player player : players) {
			if (player == null) {
				continue;
			}
			highestVp = Math.max(highestVp, player.getVictoryPoints());
		}
		for (Player player : players) {
			if (player == null) {
				continue;
			}
			if (player.getVictoryPoints() == highestVp) {
				System.out.println("Winner candidate: Player " + player.getId() + " with " + player.getVictoryPoints() + " VP");
			}
		}
	}

	private Player[] sanitizePlayers(Player[] rawPlayers) {
		Player[] normalized = new Player[4];
		for (int i = 0; i < normalized.length; i++) {
			Player provided = (rawPlayers != null && i < rawPlayers.length) ? rawPlayers[i] : null;
			normalized[i] = (provided == null) ? new Player(i + 1, new Agent(i + 1)) : provided;
		}
		return normalized;
	}

	private int normalizeMaxRounds(int rounds) {
		if (rounds < 1) {
			return 1;
		}
		if (rounds > 8192) {
			return 8192;
		}
		return rounds;
	}
}
