// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private Integer currentRound;
	/**
	 * 
	 */
	private Integer maxRounds;
	/**
	 * 
	 */
	private Boolean gameFinished;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private Dice dice;

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void playRound() {
	}

	public void resourceDistributor(int rollResult) {
		List<ResourceDistribution> distribution = getPlayersOnTile(rollResult);

		for (ResourceDistribution input: distribution) {
			Player player = input.getPlayer();
			ResourceHand resourceHand = player.getResourceHand();
			resourceHand.add(input.getResourceType(), input.getNumberOfCardsToGive());
		}
	}

	public List<ResourceDistribution> getPlayersOnTile(int rollResult) {
		List<ResourceDistribution> distribution = new ArrayList<>();
		List<Tile> sameTokenNumberTiles = new ArrayList<>();


		sameTokenNumberTiles = board.getTilesByToken(rollResult);

		for (Tile tile: sameTokenNumberTiles){
			Node[] adjacentNodes = tile.getAdjacentNodes();
			ResourceType resourceType = tile.getResourceType();
			if (resourceType == null) { //this should account for if the tile is not meant to give out resources
				continue;
			}

			for (Node node: adjacentNodes){
				Building building = node.getBuilding();
				if (building == null) {
					continue;
				}

				int numberOfCardsToGive;
				if (building instanceof Settlement) {
					numberOfCardsToGive = 1;
				}
				else if (building instanceof City) {
					numberOfCardsToGive = 2;
				} else {
					continue;
				}
				
				Player owner = building.getOwner();
				distribution.add(new ResourceDistribution(owner, numberOfCardsToGive, resourceType));
			}
		}
		
		return distribution;
	}

	/**
	 * 
	 * @return 
	 */
	public Boolean checkTerminationCondition() {
	}

	/**
	 * 
	 */
	public void printRoundSummary() {
	}

	/**
	 * 
	 * @param board 
	 * @param players 
	 * @param dice 
	 */
	public void Game(Board board, Player[] players, Dice dice) {
	}
}
