// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
class Player {
	/**
	 * 
	 */
	private Integer id;
	/**
	 * 
	 */
	private Integer victoryPoints;
	/**
	 * 
	 */
	private ResourceHand hand;
	/**
	 * 
	 */
	private List<Building> buildings = new ArrayList<>();
	/**
	 * 
	 */
	private List<Road> roads = new ArrayList<>();
	/**
	 * 
	 */
	private Agent agent;

	/**
	 * 
	 * @param game 
	 */
	public void takeTurn(Game game) {
	}

	public ResourceHand getResourceHand() {
		return hand;
	}

	/**
	 * 
	 * @param amount 
	 */
	public void collectPoints(Integer amount) {
		victoryPoints = victoryPoints + amount;
	}

	/**
	 * 
	 * @param building 
	 */
	public void addBuilding(Building building) {
		buildings.add(building);
	}

	/**
	 * 
	 * @param building 
	 */
	public void deleteBuilding(Building building) {
		buildings.remove(building);
	}

	/**
	 * 
	 * @param road 
	 */
	public void addRoad(Road road) {
		roads.add(road);
	}
}
