// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package CatanGame;
import java.util.*; 

/************************************************************/
/**
 * Class that represents a player's hand of resource cards 
 */
public class ResourceHand {
	private Map<ResourceType, Integer> resourceCount; // Map to track the quantity of each resource type in the hand 

	/**
	 * Constructor to initialize the hand
	 */
	public ResourceHand() {
		resourceCount = new HashMap<>(); 
		for (ResourceType type : ResourceType.values()) {
			resourceCount.put(type, 0); // Initialize all resource counts to 0
		}
	}
	/**
	 * Adds a specified amount of a resource type to the hand
	 * @param type Type of resource to add
	 * @param amount Quantity of resource to add 
	 */
	public void add(ResourceType type, Integer amount) {
		if (type == null || amount == null || amount <= 0) {
			return;
		}
		resourceCount.put(type, getCount(type) + amount); 
	}

	/**
	 * Removes a resource card from the hand 
	 * @param type Type of resource to remove 
	 * @param amount Quantity of resource to remove
	 */
	public void remove(ResourceType type, Integer amount) {
		if (type == null || amount == null || amount <= 0) {
			return;
		}
		int current = getCount(type);
		if (current == 0) {
			return;
		}
		int amountToRemove = Math.min(current, amount);
		resourceCount.put(type, current - amountToRemove);
	}

	/**
	 * @return Total number of resource cards in the hand   
	 */
	public int totalCards() {
		int total = 0;
		for (Integer count : resourceCount.values()) {
			total += count; 
		}
		return total; 
	}

	public int getCount(ResourceType type) {
		Integer currentCount = resourceCount.get(type);
		return currentCount == null ? 0 : currentCount;
	}

	public boolean canAfford(Map<ResourceType, Integer> cost) {
		if (cost == null || cost.isEmpty()) {
			return false;
		}
		for (Map.Entry<ResourceType, Integer> entry : cost.entrySet()) {
			if (entry.getKey() == null || entry.getValue() == null || entry.getValue() < 0) {
				return false;
			}
			if (getCount(entry.getKey()) < entry.getValue()) {
				return false;
			}
		}
		return true;
	}

	public void spend(Map<ResourceType, Integer> cost) {
		if (!canAfford(cost)) {
			return;
		}
		for (Map.Entry<ResourceType, Integer> entry : cost.entrySet()) {
			remove(entry.getKey(), entry.getValue());
		}
	}
}
