// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Enumeration for the different types of resources in the game
 */
public enum ResourceType {
	WOOD,
	BRICK,
	SHEEP,
	WHEAT,
	DESERT,
	ORE;
}
