// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package CatanGame;
import java.util.*; 

/************************************************************/
/**
 * Class that represents a player's hand of resource cards 
 */
public class ResourceHand {
	private Map<ResourceType, Integer> resourceCount; // Map to track the quantity of each resource type in the hand 

	/**
	 * Constructor to initialize the hand
	 */
	public ResourceHand() {
		resourceCount = new HashMap<>(); 
		for (ResourceType type : ResourceType.values()) {
			resourceCount.put(type, 0); // Initialize all resource counts to 0
		}
	}
	/**
	 * Adds a specified amount of a resource type to the hand
	 * @param type Type of resource to add
	 * @param amount Quantity of resources to add 
	 */
	public void add(ResourceType type, Integer amount) {
		if(amount < 0) {
			throw new IllegalArgumentException("Amount must be positive");
		}
		resourceCount.put(type, resourceCount.get(type) + amount); 
	}

	/**
	 * Removes a resource card from the hand 
	 * @param type Type of resource to remove 
	 * @param amount Quantity of resource to remove
	 */
	public void remove(ResourceType type, Integer amount) {
		if(amount < 0) {
			throw new IllegalArgumentException("Cannot remove negative amount of resources");
		}
		if(resourceCount.get(type) < amount) {
			throw new IllegalArgumentException("Insufficient resources to remove");
		}
		resourceCount.put(type, resourceCount.get(type) - amount);
	}

	/**
	 * @return Total number of resource cards in the hand 
	 */
	public int totalCards() {
		int total = 0;
		for (Integer count : resourceCount.values()) {
			total += count; 
		}
		return total; 
	}
}
