// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * Represents a road on the game board
 */
public class Road {
	/** player who owns the road */
	private Player owner;
	/** edge where road is placed */
	private Edge location;

	/**
	 * Constructor for road
	 * @param owner player who owns it
	 * @param location edge where it's placed
	 */
	public Road(Player owner, Edge location) {
		this.owner = owner;
		this.location = location;
		if (location != null && !location.edgeOccupied()) {
			location.addRoad(this);
		}
	}

	/**
	 * @return edge where road is located
	 */
	public Edge getRoadLocation() {
		return location;
	}

	/**
	 * @return owner of the road
	 */
	public Player getOwner() {
		return owner;
	}
}
