// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Edge location;

	public Road(Player owner, Edge location) {
		this.owner = owner;
		this.location = location;
		if (location != null && !location.edgeOccupied()) {
			location.addRoad(this);
		}
	}

	/**
	 * 
	 * @return 
	 */
	public Edge getRoadLocation() {
		return location;
	}

	public Player getOwner() {
		return owner;
	}
}
