// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Settlement extends Building {
	/**
	 * 
	 * @return 
	 */
	public Integer getVictoryPoints() {
		return 1;
	}
}
