// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanGame;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private Integer id;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private Integer numberToken;
	/**
	 * 
	 */
	private Node[] adjacentNodes;

	/**
	 * 
	 * @return 
	 */
	public ResourceType getResourceType() {
		return resourceType;
	}

	public Integer getNumberToken() {
		return numberToken;
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] getAdjacentNodes() {
		return adjacentNodes;
	}
}
